-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PollApi.Object exposing (..)


type AddPollCharFieldAnswerPayload
    = AddPollCharFieldAnswerPayload


type AddPollCharFieldPayload
    = AddPollCharFieldPayload


type AddPollChoiceFieldAnswerPayload
    = AddPollChoiceFieldAnswerPayload


type AddPollChoiceFieldPayload
    = AddPollChoiceFieldPayload


type AddPollMultiChoiceFieldAnswerPayload
    = AddPollMultiChoiceFieldAnswerPayload


type AddPollMultiChoiceFieldPayload
    = AddPollMultiChoiceFieldPayload


type AddPollTextFieldAnswerPayload
    = AddPollTextFieldAnswerPayload


type AddPollTextFieldPayload
    = AddPollTextFieldPayload


type CreatePoll
    = CreatePoll


type ErrorType
    = ErrorType


type Poll
    = Poll


type PollCharField
    = PollCharField


type PollCharFieldAnswer
    = PollCharFieldAnswer


type PollChoiceField
    = PollChoiceField


type PollChoiceFieldAnswer
    = PollChoiceFieldAnswer


type PollMultiChoiceField
    = PollMultiChoiceField


type PollMultiChoiceFieldAnswer
    = PollMultiChoiceFieldAnswer


type PollTextField
    = PollTextField


type PollTextFieldAnswer
    = PollTextFieldAnswer


type User
    = User
