-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PollApi.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import PollApi.Scalar exposing (defaultCodecs)


type alias Id =
    PollApi.Scalar.Id


codecs : PollApi.Scalar.Codecs Id
codecs =
    PollApi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
