# Generated by Django 4.1.5 on 2023-01-11 13:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Poll title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='PollTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100, verbose_name='Question Text')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollMultiChoiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100, verbose_name='Question Text')),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Choice'), size=None)),
                ('selected_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Selected Choices'), size=None)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollChoiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100, verbose_name='Question Text')),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Choice'), size=None)),
                ('selected_choice', models.CharField(blank=True, max_length=100, verbose_name='Selected Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollCharField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100, verbose_name='Question Text')),
                ('answer', models.CharField(blank=True, max_length=100, verbose_name='Answer')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
        ),
    ]
