# Generated by Django 4.1.5 on 2023-01-11 19:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollcharfield',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='pollchoicefield',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='pollmultichoicefield',
            name='selected_choices',
        ),
        migrations.RemoveField(
            model_name='polltextfield',
            name='answer',
        ),
        migrations.CreateModel(
            name='PollTextFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polltextfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
        migrations.CreateModel(
            name='PollMultiChoiceFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Selected Choices'), size=None)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollmultichoicefield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
        migrations.CreateModel(
            name='PollChoiceFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(max_length=100, verbose_name='Selected Choice')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollchoicefield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
        migrations.CreateModel(
            name='PollCharFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Answer')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollcharfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
    ]
