# Generated by Django 4.2.1 on 2023-06-18 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_poll_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pollcharfieldanswer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pollchoicefieldanswer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pollmultichoicefieldanswer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='polltextfieldanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pollcharfieldanswer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollresponse'),
        ),
        migrations.AddField(
            model_name='pollchoicefieldanswer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollresponse'),
        ),
        migrations.AddField(
            model_name='pollmultichoicefieldanswer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollresponse'),
        ),
        migrations.AddField(
            model_name='polltextfieldanswer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollresponse'),
        ),
        migrations.AlterUniqueTogether(
            name='pollcharfieldanswer',
            unique_together={('response', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='pollchoicefieldanswer',
            unique_together={('response', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='pollmultichoicefieldanswer',
            unique_together={('response', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='polltextfieldanswer',
            unique_together={('response', 'field')},
        ),
        migrations.RemoveField(
            model_name='pollcharfieldanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pollchoicefieldanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pollmultichoicefieldanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='polltextfieldanswer',
            name='user',
        ),
    ]
