-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PollApi.Object.AddPollChoiceFieldAnswerPayload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PollApi.InputObject
import PollApi.Interface
import PollApi.Object
import PollApi.Scalar
import PollApi.ScalarCodecs
import PollApi.Union


selectedChoice : SelectionSet String PollApi.Object.AddPollChoiceFieldAnswerPayload
selectedChoice =
    Object.selectionForField "String" "selectedChoice" [] Decode.string


field : SelectionSet PollApi.ScalarCodecs.Id PollApi.Object.AddPollChoiceFieldAnswerPayload
field =
    Object.selectionForField "ScalarCodecs.Id" "field" [] (PollApi.ScalarCodecs.codecs |> PollApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


errors :
    SelectionSet decodesTo PollApi.Object.ErrorType
    -> SelectionSet (List decodesTo) PollApi.Object.AddPollChoiceFieldAnswerPayload
errors object____ =
    Object.selectionForCompositeField "errors" [] object____ (Basics.identity >> Decode.list)


pollChoiceFieldAnswer :
    SelectionSet decodesTo PollApi.Object.PollChoiceFieldAnswer
    -> SelectionSet (Maybe decodesTo) PollApi.Object.AddPollChoiceFieldAnswerPayload
pollChoiceFieldAnswer object____ =
    Object.selectionForCompositeField "pollChoiceFieldAnswer" [] object____ (Basics.identity >> Decode.nullable)


clientMutationId : SelectionSet (Maybe String) PollApi.Object.AddPollChoiceFieldAnswerPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)
