-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PollApi.Object.AddPollMultiChoiceFieldAnswerPayload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PollApi.InputObject
import PollApi.Interface
import PollApi.Object
import PollApi.Scalar
import PollApi.ScalarCodecs
import PollApi.Union


selectedChoices : SelectionSet String PollApi.Object.AddPollMultiChoiceFieldAnswerPayload
selectedChoices =
    Object.selectionForField "String" "selectedChoices" [] Decode.string


field : SelectionSet PollApi.ScalarCodecs.Id PollApi.Object.AddPollMultiChoiceFieldAnswerPayload
field =
    Object.selectionForField "ScalarCodecs.Id" "field" [] (PollApi.ScalarCodecs.codecs |> PollApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


errors :
    SelectionSet decodesTo PollApi.Object.ErrorType
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PollApi.Object.AddPollMultiChoiceFieldAnswerPayload
errors object____ =
    Object.selectionForCompositeField "errors" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


pollMultiChoiceFieldAnswer :
    SelectionSet decodesTo PollApi.Object.PollMultiChoiceFieldAnswer
    -> SelectionSet (Maybe decodesTo) PollApi.Object.AddPollMultiChoiceFieldAnswerPayload
pollMultiChoiceFieldAnswer object____ =
    Object.selectionForCompositeField "pollMultiChoiceFieldAnswer" [] object____ (Basics.identity >> Decode.nullable)


clientMutationId : SelectionSet (Maybe String) PollApi.Object.AddPollMultiChoiceFieldAnswerPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)
