-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PollApi.Object.AddPollTextFieldAnswerPayload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PollApi.InputObject
import PollApi.Interface
import PollApi.Object
import PollApi.Scalar
import PollApi.ScalarCodecs
import PollApi.Union


answer : SelectionSet String PollApi.Object.AddPollTextFieldAnswerPayload
answer =
    Object.selectionForField "String" "answer" [] Decode.string


field : SelectionSet PollApi.ScalarCodecs.Id PollApi.Object.AddPollTextFieldAnswerPayload
field =
    Object.selectionForField "ScalarCodecs.Id" "field" [] (PollApi.ScalarCodecs.codecs |> PollApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


errors :
    SelectionSet decodesTo PollApi.Object.ErrorType
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PollApi.Object.AddPollTextFieldAnswerPayload
errors object____ =
    Object.selectionForCompositeField "errors" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


pollTextFieldAnswer :
    SelectionSet decodesTo PollApi.Object.PollTextFieldAnswer
    -> SelectionSet (Maybe decodesTo) PollApi.Object.AddPollTextFieldAnswerPayload
pollTextFieldAnswer object____ =
    Object.selectionForCompositeField "pollTextFieldAnswer" [] object____ (Basics.identity >> Decode.nullable)


clientMutationId : SelectionSet (Maybe String) PollApi.Object.AddPollTextFieldAnswerPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)
