-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PollApi.Object.AddPollMultiChoiceFieldPayload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PollApi.InputObject
import PollApi.Interface
import PollApi.Object
import PollApi.Scalar
import PollApi.ScalarCodecs
import PollApi.Union


pollMultiChoiceField :
    SelectionSet decodesTo PollApi.Object.PollMultiChoiceField
    -> SelectionSet (Maybe decodesTo) PollApi.Object.AddPollMultiChoiceFieldPayload
pollMultiChoiceField object____ =
    Object.selectionForCompositeField "pollMultiChoiceField" [] object____ (Basics.identity >> Decode.nullable)


errors :
    SelectionSet decodesTo PollApi.Object.ErrorType
    -> SelectionSet (List decodesTo) PollApi.Object.AddPollMultiChoiceFieldPayload
errors object____ =
    Object.selectionForCompositeField "errors" [] object____ (Basics.identity >> Decode.list)


clientMutationId : SelectionSet (Maybe String) PollApi.Object.AddPollMultiChoiceFieldPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)
