-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PollApi.Object.PollTextField exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PollApi.InputObject
import PollApi.Interface
import PollApi.Object
import PollApi.Scalar
import PollApi.ScalarCodecs
import PollApi.Union


id : SelectionSet PollApi.ScalarCodecs.Id PollApi.Object.PollTextField
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PollApi.ScalarCodecs.codecs |> PollApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


text : SelectionSet String PollApi.Object.PollTextField
text =
    Object.selectionForField "String" "text" [] Decode.string


textFieldAnswers :
    SelectionSet decodesTo PollApi.Object.PollTextFieldAnswer
    -> SelectionSet (List decodesTo) PollApi.Object.PollTextField
textFieldAnswers object____ =
    Object.selectionForCompositeField "textFieldAnswers" [] object____ (Basics.identity >> Decode.list)
