-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PollApi.Object.PollMultiChoiceField exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PollApi.InputObject
import PollApi.Interface
import PollApi.Object
import PollApi.Scalar
import PollApi.ScalarCodecs
import PollApi.Union


id : SelectionSet PollApi.ScalarCodecs.Id PollApi.Object.PollMultiChoiceField
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PollApi.ScalarCodecs.codecs |> PollApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


text : SelectionSet String PollApi.Object.PollMultiChoiceField
text =
    Object.selectionForField "String" "text" [] Decode.string


choices : SelectionSet (List String) PollApi.Object.PollMultiChoiceField
choices =
    Object.selectionForField "(List String)" "choices" [] (Decode.string |> Decode.list)


multichoiceFieldAnswers :
    SelectionSet decodesTo PollApi.Object.PollMultiChoiceFieldAnswer
    -> SelectionSet (List decodesTo) PollApi.Object.PollMultiChoiceField
multichoiceFieldAnswers object____ =
    Object.selectionForCompositeField "multichoiceFieldAnswers" [] object____ (Basics.identity >> Decode.list)
